In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/afoone/caipc-laberit-jul2022/master/titanic.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data.shape

(891, 12)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
data['Ticket'].unique()

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '113572', '36973', '347088', 'PC 17605', '2661',
       'C.A. 29395', 'S.P. 3464', '3101281', '315151', 'C.A. 33111',
       'S.O.C. 14879', '2680', '1601', '348123', '349208', '374746',
       '248738', '364516', '345767', '345779', '330932', '113059',
       'SO/C 14885', '31012

In [7]:
 titanic = data.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [8]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [9]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [10]:
gender_dummies = pd.get_dummies(titanic['Sex'], prefix='gender')

In [12]:
embarked_dummies = pd.get_dummies(titanic['Embarked'], prefix='embarked')
# categorizar la variable p_class
class_dummies = pd.get_dummies(titanic['Pclass'], prefix='class')
titanic = titanic.join(gender_dummies).join(embarked_dummies).join(class_dummies)

In [13]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  \
0           0       3    male  22.0      1      0   7.2500        S   
1           1       1  female  38.0      1      0  71.2833        C   
2           1       3  female  26.0      0      0   7.9250        S   
3           1       1  female  35.0      1      0  53.1000        S   
4           0       3    male  35.0      0      0   8.0500        S   
..        ...     ...     ...   ...    ...    ...      ...      ...   
886         0       2    male  27.0      0      0  13.0000        S   
887         1       1  female  19.0      0      0  30.0000        S   
888         0       3  female   NaN      1      2  23.4500        S   
889         1       1    male  26.0      0      0  30.0000        C   
890         0       3    male  32.0      0      0   7.7500        Q   

     gender_female  gender_male  embarked_C  embarked_Q  embarked_S  class_1  \
0                0            1           0           0           1        0   
1                1            0           1           0           0        1   
2                1            0           0           0           1        0   
3                1            0           0           0           1        1   
4                0            1           0           0           1        0   
..             ...          ...         ...         ...         ...      ...   
886              0            1           0           0           1        0   
887              1            0           0           0           1        1   
888              1            0           0           0           1        0   
889              0            1           1           0           0        1   
890              0            1           0           1           0        0   

     class_2  class_3  
0          0        1  
1          0        0  
2          0        1  
3          0        0  
4          0        1  
..       ...      ...  
886        1        0  
887        0        0  
888        0        1  
889        0        0  
890        0        1  

[891 rows x 16 columns]

In [14]:
titanic = titanic.drop(['Sex', 'Embarked', 'Pclass'], axis=1)

In [15]:
titanic

Survived   Age  SibSp  Parch     Fare  gender_female  gender_male  \
0           0  22.0      1      0   7.2500              0            1   
1           1  38.0      1      0  71.2833              1            0   
2           1  26.0      0      0   7.9250              1            0   
3           1  35.0      1      0  53.1000              1            0   
4           0  35.0      0      0   8.0500              0            1   
..        ...   ...    ...    ...      ...            ...          ...   
886         0  27.0      0      0  13.0000              0            1   
887         1  19.0      0      0  30.0000              1            0   
888         0   NaN      1      2  23.4500              1            0   
889         1  26.0      0      0  30.0000              0            1   
890         0  32.0      0      0   7.7500              0            1   

     embarked_C  embarked_Q  embarked_S  class_1  class_2  class_3  
0             0           0           1        0        0        1  
1             1           0           0        1        0        0  
2             0           0           1        0        0        1  
3             0           0           1        1        0        0  
4             0           0           1        0        0        1  
..          ...         ...         ...      ...      ...      ...  
886           0           0           1        0        1        0  
887           0           0           1        1        0        0  
888           0           0           1        0        0        1  
889           1           0           0        1        0        0  
890           0           1           0        0        0        1  

[891 rows x 13 columns]

# Seleccionar variables

In [16]:
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [17]:
# instanciamos la regresión logística
lr = LogisticRegression()


In [24]:
titanic.columns

Index(['Survived', 'Age', 'SibSp', 'Parch', 'Fare', 'gender_female',
       'gender_male', 'embarked_C', 'embarked_Q', 'embarked_S', 'class_1',
       'class_2', 'class_3'],
      dtype='object')

In [28]:
titanic_dropna = titanic.dropna()

In [30]:
titanic_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Survived       714 non-null    int64  
 1   Age            714 non-null    float64
 2   SibSp          714 non-null    int64  
 3   Parch          714 non-null    int64  
 4   Fare           714 non-null    float64
 5   gender_female  714 non-null    uint8  
 6   gender_male    714 non-null    uint8  
 7   embarked_C     714 non-null    uint8  
 8   embarked_Q     714 non-null    uint8  
 9   embarked_S     714 non-null    uint8  
 10  class_1        714 non-null    uint8  
 11  class_2        714 non-null    uint8  
 12  class_3        714 non-null    uint8  
dtypes: float64(2), int64(3), uint8(8)
memory usage: 39.0 KB


In [34]:
# hacer una feature selection
rfe = RFE(lr, n_features_to_select=4)
rfe.fit(titanic_dropna[['Age', 'SibSp', 'Parch', 'Fare', 'gender_female',
       'gender_male', 'embarked_C', 'embarked_Q', 'embarked_S', 'class_1',
       'class_2', 'class_3']], titanic_dropna['Survived'])

/Users/atienda/miniforge3/envs/caipc/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/atienda/miniforge3/envs/caipc/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/l

RFE(estimator=LogisticRegression(), n_features_to_select=4)

In [47]:
titanic_dropna['class_3'].sum()

355

In [35]:
rfe.support_

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [37]:
rfe.ranking_

array([6, 4, 7, 9, 1, 1, 2, 3, 5, 1, 8, 1])

In [48]:
z = zip(['Age', 'SibSp', 'Parch', 'Fare', 'gender_female',
       'gender_male', 'embarked_C', 'embarked_Q', 'embarked_S', 'class_1',
       'class_2', 'class_3'], rfe.support_, rfe.ranking_)
list(z)

[('Age', False, 6),
 ('SibSp', False, 4),
 ('Parch', False, 7),
 ('Fare', False, 9),
 ('gender_female', True, 1),
 ('gender_male', True, 1),
 ('embarked_C', False, 2),
 ('embarked_Q', False, 3),
 ('embarked_S', False, 5),
 ('class_1', True, 1),
 ('class_2', False, 8),
 ('class_3', True, 1)]

In [49]:
lr.fit(titanic_dropna[['gender_male', 'gender_female', 'class_1', 'class_3']], titanic_dropna['Survived'])

LogisticRegression()

In [51]:
lr.score(titanic_dropna[['gender_male', 'gender_female', 'class_1', 'class_3']], titanic_dropna['Survived'])

0.7801120448179272

In [52]:
titanic_woage = titanic.dropna(axis = 1)

In [53]:
titanic_woage

Survived  SibSp  Parch     Fare  gender_female  gender_male  embarked_C  \
0           0      1      0   7.2500              0            1           0   
1           1      1      0  71.2833              1            0           1   
2           1      0      0   7.9250              1            0           0   
3           1      1      0  53.1000              1            0           0   
4           0      0      0   8.0500              0            1           0   
..        ...    ...    ...      ...            ...          ...         ...   
886         0      0      0  13.0000              0            1           0   
887         1      0      0  30.0000              1            0           0   
888         0      1      2  23.4500              1            0           0   
889         1      0      0  30.0000              0            1           1   
890         0      0      0   7.7500              0            1           0   

     embarked_Q  embarked_S  class_1  class_2  class_3  
0             0           1        0        0        1  
1             0           0        1        0        0  
2             0           1        0        0        1  
3             0           1        1        0        0  
4             0           1        0        0        1  
..          ...         ...      ...      ...      ...  
886           0           1        0        1        0  
887           0           1        1        0        0  
888           0           1        0        0        1  
889           0           0        1        0        0  
890           1           0        0        0        1  

[891 rows x 12 columns]

In [55]:
# hacer una feature selection
rfe = RFE(lr, n_features_to_select=4)
rfe.fit(titanic_woage[['SibSp', 'Parch', 'Fare', 'gender_female',
       'gender_male', 'embarked_C', 'embarked_Q', 'embarked_S', 'class_1',
       'class_2', 'class_3']], titanic_woage['Survived'])

RFE(estimator=LogisticRegression(), n_features_to_select=4)

In [56]:
z = zip(['SibSp', 'Parch', 'Fare', 'gender_female',
       'gender_male', 'embarked_C', 'embarked_Q', 'embarked_S', 'class_1',
       'class_2', 'class_3'], rfe.support_, rfe.ranking_)
list(z)

[('SibSp', False, 3),
 ('Parch', False, 6),
 ('Fare', False, 8),
 ('gender_female', True, 1),
 ('gender_male', True, 1),
 ('embarked_C', False, 4),
 ('embarked_Q', False, 7),
 ('embarked_S', False, 2),
 ('class_1', True, 1),
 ('class_2', False, 5),
 ('class_3', True, 1)]

In [61]:
lr_full = LogisticRegression()
lr_full.fit(titanic_woage[[ 'gender_female',
       'gender_male','class_1',
       'class_3']], titanic_woage['Survived'])
lr_full.score(titanic_woage[[ 'gender_female',
       'gender_male','class_1',
       'class_3']], titanic_woage['Survived'])

0.7867564534231201

# validación

In [63]:
from sklearn.model_selection import train_test_split

In [65]:
train, test = train_test_split(titanic_woage, test_size=0.2, random_state=0)

In [67]:
train.shape

(712, 12)

In [69]:
test.shape

(179, 12)

In [71]:
lr_full = LogisticRegression()
lr_full.fit(train[[ 'gender_female',
       'gender_male','class_1',
       'class_3']], train['Survived'])
lr_full.score(train[[ 'gender_female',
       'gender_male','class_1',
       'class_3']], train['Survived'])

0.7865168539325843

In [76]:
test['predicted'] = lr_full.predict(test[[ 'gender_female',
       'gender_male','class_1',
       'class_3']])

In [85]:
test[test['Survived']==test['predicted']]['predicted'].count() / len(test)

0.7877094972067039

In [87]:
lr_full.predict(test[[ 'gender_female',
       'gender_male','class_1',
       'class_3']])

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0])

In [92]:
lr_full.predict_proba(
    test[[ 'gender_female',
       'gender_male','class_1',
       'class_3']]
)[:,1]

array([0.10963322, 0.10963322, 0.10963322, 0.8919232 , 0.61008348,
       0.39373998, 0.8919232 , 0.8919232 , 0.39373998, 0.61008348,
       0.10963322, 0.80438956, 0.10963322, 0.80438956, 0.8919232 ,
       0.61008348, 0.10963322, 0.24449388, 0.10963322, 0.10963322,
       0.24449388, 0.8919232 , 0.10963322, 0.39373998, 0.61008348,
       0.8919232 , 0.10963322, 0.61008348, 0.80438956, 0.61008348,
       0.10963322, 0.80438956, 0.10963322, 0.39373998, 0.10963322,
       0.39373998, 0.10963322, 0.24449388, 0.24449388, 0.24449388,
       0.39373998, 0.10963322, 0.10963322, 0.10963322, 0.8919232 ,
       0.10963322, 0.10963322, 0.8919232 , 0.24449388, 0.39373998,
       0.39373998, 0.39373998, 0.80438956, 0.10963322, 0.39373998,
       0.24449388, 0.39373998, 0.61008348, 0.10963322, 0.10963322,
       0.10963322, 0.61008348, 0.8919232 , 0.39373998, 0.61008348,
       0.10963322, 0.8919232 , 0.24449388, 0.80438956, 0.8919232 ,
       0.80438956, 0.39373998, 0.39373998, 0.10963322, 0.10963

In [94]:
test['pro_surv'] = lr_full.predict_proba(
    test[[ 'gender_female',
       'gender_male','class_1',
       'class_3']]
)[:,1]

In [95]:
test

Survived  SibSp  Parch      Fare  gender_female  gender_male  embarked_C  \
495         0      0      0   14.4583              0            1           1   
648         0      0      0    7.5500              0            1           0   
278         0      4      1   29.1250              0            1           0   
31          1      1      0  146.5208              1            0           1   
255         1      0      2   15.2458              1            0           1   
..        ...    ...    ...       ...            ...          ...         ...   
780         1      0      0    7.2292              1            0           1   
837         0      0      0    8.0500              0            1           0   
215         1      1      0  113.2750              1            0           1   
833         0      0      0    7.8542              0            1           0   
372         0      0      0    8.0500              0            1           0   

     embarked_Q  embarked_S  class_1  class_2  class_3  predicted  pro_surv  
495           0           0        0        0        1          0  0.109633  
648           0           1        0        0        1          0  0.109633  
278           1           0        0        0        1          0  0.109633  
31            0           0        1        0        0          1  0.891923  
255           0           0        0        0        1          1  0.610083  
..          ...         ...      ...      ...      ...        ...       ...  
780           0           0        0        0        1          1  0.610083  
837           0           1        0        0        1          0  0.109633  
215           0           0        1        0        0          1  0.891923  
833           0           1        0        0        1          0  0.109633  
372           0           1        0        0        1          0  0.109633  

[179 rows x 14 columns]

In [97]:
test[test['pro_surv']>0.89]

Survived  SibSp  Parch      Fare  gender_female  gender_male  embarked_C  \
31          1      1      0  146.5208              1            0           1   
609         1      0      0  153.4625              1            0           0   
318         1      0      2  164.8667              1            0           0   
310         1      0      0   83.1583              1            0           1   
708         1      0      0  151.5500              1            0           0   
319         1      1      1  134.5000              1            0           1   
230         1      1      0   83.4750              1            0           0   
311         1      2      2  262.3750              1            0           1   
496         1      1      0   78.2667              1            0           1   
796         1      0      0   25.9292              1            0           0   
887         1      0      0   30.0000              1            0           0   
627         1      0      0   77.9583              1            0           0   
380         1      0      0  227.5250              1            0           1   
523         1      0      1   57.9792              1            0           1   
356         1      0      1   55.0000              1            0           0   
700         1      1      0  227.5250              1            0           1   
412         1      1      0   90.0000              1            0           0   
299         1      0      1  247.5208              1            0           1   
513         1      1      0   59.4000              1            0           1   
1           1      1      0   71.2833              1            0           1   
215         1      1      0  113.2750              1            0           1   

     embarked_Q  embarked_S  class_1  class_2  class_3  predicted  pro_surv  
31            0           0        1        0        0          1  0.891923  
609           0           1        1        0        0          1  0.891923  
318           0           1        1        0        0          1  0.891923  
310           0           0        1        0        0          1  0.891923  
708           0           1        1        0        0          1  0.891923  
319           0           0        1        0        0          1  0.891923  
230           0           1        1        0        0          1  0.891923  
311           0           0        1        0        0          1  0.891923  
496           0           0        1        0        0          1  0.891923  
796           0           1        1        0        0          1  0.891923  
887           0           1        1        0        0          1  0.891923  
627           0           1        1        0        0          1  0.891923  
380           0           0        1        0        0          1  0.891923  
523           0           0        1        0        0          1  0.891923  
356           0           1        1        0        0          1  0.891923  
700           0           0        1        0        0          1  0.891923  
412           1           0        1        0        0          1  0.891923  
299           0           0        1        0        0          1  0.891923  
513           0           0        1        0        0          1  0.891923  
1             0           0        1        0        0          1  0.891923  
215           0           0        1        0        0          1  0.891923

# validación cruzada

In [102]:
from sklearn.model_selection import cross_val_score

values = cross_val_score(
    LogisticRegression(), 
    titanic_woage[[ 'gender_female',
       'gender_male','class_1',
       'class_3']] ,
    titanic_woage['Survived'],
    scoring='accuracy',
    cv = 10
)

In [104]:
values.mean()

0.786729088639201

In [105]:
values.std()

0.028599350013463757

In [106]:
values

array([0.81111111, 0.79775281, 0.76404494, 0.84269663, 0.79775281,
       0.7752809 , 0.76404494, 0.74157303, 0.80898876, 0.76404494])